# Generated by Django 4.2.2 on 2023-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1023)),
                ('country', models.CharField(max_length=1023)),
                ('city', models.CharField(max_length=1023)),
            ],
        ),
    ]
