# Generated by Django 4.2.2 on 2023-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.CharField(default='null', max_length=1023),
            preserve_default=False,
        ),
    ]
