# Generated by Django 4.2.2 on 2023-06-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='programs_serialized',
            field=models.CharField(default='', max_length=65535),
            preserve_default=False,
        ),
    ]
