# Generated by Django 4.2.2 on 2023-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_university_programs_serialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='lat',
            field=models.CharField(default='0', max_length=65535),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='lon',
            field=models.CharField(default='0', max_length=65535),
            preserve_default=False,
        ),
    ]
