# Generated by Django 4.2.2 on 2023-07-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='number_id',
            field=models.CharField(default='0', max_length=1023),
            preserve_default=False,
        ),
    ]
